import {
  Accessibility,
  Activity,
  AlertTriangle,
  Ambulance,
  Award,
  Baby,
  Banknote,
  Bell,
  BellRing,
  Biohazard,
  Bone,
  Brain,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clipboard,
  ClipboardList,
  Clock,
  Compass,
  Crosshair,
  Eye,
  EyeOff,
  FileBadge,
  FileCheck,
  FileClock,
  FilePen,
  FileText,
  FlaskConical,
  FolderOpen,
  Globe,
  Handshake,
  HardHat,
  Heart,
  HelpCircle,
  Home,
  Inbox,
  Info,
  LayoutDashboard,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Microscope,
  Minus,
  Moon,
  Navigation,
  Newspaper,
  Phone,
  Pill,
  Plus,
  RefreshCw,
  Ribbon,
  Scale,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Siren,
  Sparkles,
  Square,
  Star,
  Stethoscope,
  Sun,
  TableProperties,
  Target,
  Truck,
  User,
  Users,
  X,
  XCircle,
} from 'lucide-react'

const Icons = {
  dashboard: LayoutDashboard,
  users: Users,
  doctor: Stethoscope,
  emergency: Siren,
  ambulance: Ambulance,
  appointments: Calendar,
  consultations: MessageCircle,
  availability: CalendarClock,
  prescriptions: ClipboardList,
  events: Sparkles,
  news: Newspaper,
  programmes: Compass,
  partners: Handshake,
  logs: FileClock,
  reports: FileClock,
  settings: Settings,
  hospital: Building2,
  departments: TableProperties,
  vehicles: Truck,
  rides: Ambulance,
  'repeat-prescription': RefreshCw,
  fees: Banknote,
  forms: Clipboard,
  records: FolderOpen,
  notifications: Bell,
  messages: MessageSquare,
  certificates: Award,
  map: Map,
  'map-pin': MapPin,
  mail: Mail,
  'message-circle': MessageCircle,
  alerts: BellRing,
  profile: User,
  chat: MessageCircle,
  rx: ClipboardList,
  billing: Banknote,
  support: HelpCircle,
  help: HelpCircle,
  home: Home,
  user: User,
  bell: Bell,
  chevDown: ChevronDown,
  chevUp: ChevronUp,
  signout: LogOut,
  policy: FileCheck,
  terms: ScrollText,
  sun: Sun,
  moon: Moon,
  accessibility: Accessibility,
  phone: Phone,
  brain: Brain,
  heart: Heart,
  bone: Bone,
  baby: Baby,
  microscope: Microscope,
  lab: FlaskConical,
  target: Target,
  shield: ShieldCheck,
  clock: Clock,
  lock: Lock,
  document: FileText,
  pill: Pill,
  scale: Scale,
  ribbon: Ribbon,
  biohazard: Biohazard,
  handshake: Handshake,
  id: FileBadge,
  globe: Globe,
  search: Search,
  send: Send,
  inbox: Inbox,
  x: X,
  close: X,
  warning: AlertTriangle,
  info: Info,
  success: CheckCircle2,
  error: XCircle,
  check: Check,
  eye: Eye,
  'eye-off': EyeOff,
  plus: Plus,
  minus: Minus,
  crosshair: Crosshair,
  refresh: RefreshCw,
  navigate: Navigation,
  activity: Activity,
  hardhat: HardHat,
  pen: FilePen,
  star: Star,
  square: Square,
}

const AppIcon = ({ name, size = 20, color = 'currentColor', strokeWidth = 2, className, ...rest }) => {
  const Cmp = Icons[name]
  if (!Cmp) return null
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...rest} />
}

const EMOJI_TO_ICON = {
  '📋': 'forms',
  '📄': 'document',
  '📝': 'pen',
  '🩺': 'doctor',
  '🚑': 'ambulance',
  '💊': 'pill',
  '💬': 'chat',
  '❤️': 'heart',
  '🧠': 'brain',
  '🦴': 'bone',
  '👶': 'baby',
  '🔬': 'microscope',
  '🏥': 'hospital',
  '🎗️': 'ribbon',
  '🤰': 'baby',
  '⚖️': 'scale',
  '🔒': 'lock',
  '🦠': 'biohazard',
  '🤝': 'handshake',
  '🕐': 'clock',
  '💰': 'fees',
  '🎯': 'target',
  '👥': 'users',
  '🛡️': 'shield',
  '⏰': 'clock',
  '👨‍⚕️': 'doctor',
  '🔔': 'notifications',
  '⭐': 'award',
  '✅': 'success',
}

const FormIcon = ({ value, size = 32, color = 'currentColor', strokeWidth = 2 }) => {
  const key = EMOJI_TO_ICON[value] || value
  if (Icons[key]) {
    return <AppIcon name={key} size={size} color={color} strokeWidth={strokeWidth} />
  }
  return <AppIcon name="forms" size={size} color={color} strokeWidth={strokeWidth} />
}

export { Icons, AppIcon, FormIcon, EMOJI_TO_ICON }
export default AppIcon